//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KODMARK_new.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KODMARK_new.Resources.AboutText", typeof(AboutText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket ve ambalaj sektöründe faaliyet gösteren firmamız 2012 yılında, sektöre emek vermiş tecrübeli bir ekip tarafından kurulmuş olup, toplamda 1.000 m2 kapalı alanda hizmet vermektedir..
        /// </summary>
        public static string b_aciklama {
            get {
                return ResourceManager.GetString("b_aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KODMARK.
        /// </summary>
        public static string b_baslik1 {
            get {
                return ResourceManager.GetString("b_baslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKINDA.
        /// </summary>
        public static string b_baslik2 {
            get {
                return ResourceManager.GetString("b_baslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKIMIZDA.
        /// </summary>
        public static string h_baslik {
            get {
                return ResourceManager.GetString("h_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmamız alanında uzman ve dinamik kadrosu ile sorumluluğu altındaki işlerin kurallara uygun bir şekilde, yüksek kalitede ve zamanında sonuçlandırılmasını sağlar. 
        ///Gıda, Kimya, İnşaat, Tekstil, Lojistik başta olmak üzere diğer tüm sektörlerde kullanılan etiket ve termal transfer ribon üretiminde lider şirketlerden birisi olup, bunların yanı sıra, barkod donanımları, otomatik etiketleme makinaları, yedek parça ve sarf malzemelerini müşterileri ile güvenle buluşturan bir kuruluştur..
        /// </summary>
        public static string h1_aciklama {
            get {
                return ResourceManager.GetString("h1_aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NİÇİN BİZ?.
        /// </summary>
        public static string h1_baslik {
            get {
                return ResourceManager.GetString("h1_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulduğu tarihten bu yana yurt içinde hizmet veren firmamız, 2017 itibariyle de 9 ülkeye ihracat yapmaya başlamıştır. Türkiye’de sürdürdüğü büyüme ile birlikte, daha çok ülkeye ulaşma hedefine adım adım yaklaşan, sürekli gelişim amacı gözeten bir firma olma yolunda başarısını sürdürmektedir.
        ///Kalite standartları ve çevresel duyarlılıkla üretim yapan firmamız ISO 9001: 2015 güvencesi altında, müşterilerinin farklı ihtiyaçlarını karşılayabilmek adına AR-GE ve ÜR-GE çalışmalarına, üretim teknolojilerine, özel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string h2__aciklama {
            get {
                return ResourceManager.GetString("h2._aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİZ NE YAPIYORUZ?.
        /// </summary>
        public static string h2_baslik {
            get {
                return ResourceManager.GetString("h2_baslik", resourceCulture);
            }
        }
    }
}
