//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodmark.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BarcodeReaderText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BarcodeReaderText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodmark.Resources.BarcodeReaderText", typeof(BarcodeReaderText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARKOD.
        /// </summary>
        public static string baslik1 {
            get {
                return ResourceManager.GetString("baslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKUYUCU.
        /// </summary>
        public static string baslik2 {
            get {
                return ResourceManager.GetString("baslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCD OKUYUCU.
        /// </summary>
        public static string ccd {
            get {
                return ResourceManager.GetString("ccd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇOK YÖNLÜ LAZER OKUYUCU.
        /// </summary>
        public static string cokluLazer {
            get {
                return ResourceManager.GetString("cokluLazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDUSTRİYEL OKUYUCU.
        /// </summary>
        public static string endüstriyel {
            get {
                return ResourceManager.GetString("endüstriyel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGER OKUYUCU.
        /// </summary>
        public static string imager {
            get {
                return ResourceManager.GetString("imager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KABLOSUZ OKUYUCU.
        /// </summary>
        public static string kablosuz {
            get {
                return ResourceManager.GetString("kablosuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAREKOD OKUYUCU.
        /// </summary>
        public static string karekod {
            get {
                return ResourceManager.GetString("karekod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANYETİK OKUYUCU.
        /// </summary>
        public static string manyetik {
            get {
                return ResourceManager.GetString("manyetik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEK ÇİZGİLİ LAZER OKUYUCU.
        /// </summary>
        public static string tekliLazer {
            get {
                return ResourceManager.GetString("tekliLazer", resourceCulture);
            }
        }
    }
}
