//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KODMARK_new.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BarcodeAccessoriesText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BarcodeAccessoriesText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KODMARK_new.Resources.BarcodeAccessoriesText", typeof(BarcodeAccessoriesText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETİKET APLİKATÖRÜ.
        /// </summary>
        public static string altBaslik {
            get {
                return ResourceManager.GetString("altBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKSESUARLAR.
        /// </summary>
        public static string anaBaslik {
            get {
                return ResourceManager.GetString("anaBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOWA APF-60.
        /// </summary>
        public static string apf60_baslik {
            get {
                return ResourceManager.GetString("apf60_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOWA APN-100.
        /// </summary>
        public static string apn100_baslik {
            get {
                return ResourceManager.GetString("apn100_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100mm etiket genişliği.
        /// </summary>
        public static string apn100_ozellik3 {
            get {
                return ResourceManager.GetString("apn100_ozellik3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOWA APN-30.
        /// </summary>
        public static string apn30_baslik {
            get {
                return ResourceManager.GetString("apn30_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patentli etiket sensörü.
        /// </summary>
        public static string apn30_ozellik1 {
            get {
                return ResourceManager.GetString("apn30_ozellik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket sıkışma önleyici.
        /// </summary>
        public static string apn30_ozellik2 {
            get {
                return ResourceManager.GetString("apn30_ozellik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-30mm etiket genişliği.
        /// </summary>
        public static string apn30_ozellik3 {
            get {
                return ResourceManager.GetString("apn30_ozellik3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlanabilir başlık.
        /// </summary>
        public static string apn30_ozellik4 {
            get {
                return ResourceManager.GetString("apn30_ozellik4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolay kavrama.
        /// </summary>
        public static string apn30_ozellik5 {
            get {
                return ResourceManager.GetString("apn30_ozellik5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şekilli kenar desteği.
        /// </summary>
        public static string apn60_ozellik2 {
            get {
                return ResourceManager.GetString("apn60_ozellik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60mm etiket genişliği.
        /// </summary>
        public static string apn60_ozellik4 {
            get {
                return ResourceManager.GetString("apn60_ozellik4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARKOD YAZICI AKSESUARLARI.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket Genişliği:.
        /// </summary>
        public static string etiketGenislik {
            get {
                return ResourceManager.GetString("etiketGenislik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETİKET SARICI.
        /// </summary>
        public static string etiketSarici {
            get {
                return ResourceManager.GetString("etiketSarici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203 mm (Max.).
        /// </summary>
        public static string g_cap {
            get {
                return ResourceManager.GetString("g_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25,4 mm-120 mm.
        /// </summary>
        public static string g_genislik {
            get {
                return ResourceManager.GetString("g_genislik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İç Sarım veya Dış Sarım.
        /// </summary>
        public static string g_sarimYon {
            get {
                return ResourceManager.GetString("g_sarimYon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 304,8 mm/saniye (Max.).
        /// </summary>
        public static string g_sarmahiz {
            get {
                return ResourceManager.GetString("g_sarmahiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GODEX T-10.
        /// </summary>
        public static string godexBaslik1 {
            get {
                return ResourceManager.GetString("godexBaslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖZELLİKLER.
        /// </summary>
        public static string ozellik {
            get {
                return ResourceManager.GetString("ozellik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rulo Dış Çapı:.
        /// </summary>
        public static string ruloCap {
            get {
                return ResourceManager.GetString("ruloCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sarım Yönü:.
        /// </summary>
        public static string sarimYon {
            get {
                return ResourceManager.GetString("sarimYon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sarma Hızı:.
        /// </summary>
        public static string sarmaHiz {
            get {
                return ResourceManager.GetString("sarmaHiz", resourceCulture);
            }
        }
    }
}
