//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KODMARK_new.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BlankLabelText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlankLabelText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KODMARK_new.Resources.BlankLabelText", typeof(BlankLabelText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASKISIZ ETİKETLER.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastyre Etiket.
        /// </summary>
        public static string Fastyre {
            get {
                return ResourceManager.GetString("Fastyre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floresan Etiket.
        /// </summary>
        public static string Floresan {
            get {
                return ResourceManager.GetString("Floresan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kırılgan Etiket.
        /// </summary>
        public static string kirilgan {
            get {
                return ResourceManager.GetString("kirilgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuşe Etiket.
        /// </summary>
        public static string kuse {
            get {
                return ResourceManager.GetString("kuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuyumcu ve Optik Etiketi.
        /// </summary>
        public static string KuyumcuOptik {
            get {
                return ResourceManager.GetString("KuyumcuOptik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP Opak Etiket.
        /// </summary>
        public static string ppOpak {
            get {
                return ResourceManager.GetString("ppOpak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silvermat Etiket.
        /// </summary>
        public static string silvermat {
            get {
                return ResourceManager.GetString("silvermat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termal Etiket.
        /// </summary>
        public static string termal {
            get {
                return ResourceManager.GetString("termal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vellum Etiket.
        /// </summary>
        public static string vellum {
            get {
                return ResourceManager.GetString("vellum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yem ve Çuval Etiketi.
        /// </summary>
        public static string YemCuval {
            get {
                return ResourceManager.GetString("YemCuval", resourceCulture);
            }
        }
    }
}
