//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodmark.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DesktopPrinterText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesktopPrinterText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodmark.Resources.DesktopPrinterText", typeof(DesktopPrinterText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104 mm Baskı Genişliği.
        /// </summary>
        public static string a_BaskiGenislik {
            get {
                return ResourceManager.GetString("a_BaskiGenislik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. 102 mm.
        /// </summary>
        public static string a_BaskiHizi {
            get {
                return ResourceManager.GetString("a_BaskiHizi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direk Termal / Termal Transfer Barkod Yazıcı.
        /// </summary>
        public static string a_BaskiMetod {
            get {
                return ResourceManager.GetString("a_BaskiMetod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.092 mm Baskı Uzunluğu.
        /// </summary>
        public static string a_BaskiUzunluk {
            get {
                return ResourceManager.GetString("a_BaskiUzunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARGOX.
        /// </summary>
        public static string a_Baslik1 {
            get {
                return ResourceManager.GetString("a_Baslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS-214 PLUS.
        /// </summary>
        public static string a_Baslik2 {
            get {
                return ResourceManager.GetString("a_Baslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203 DPI.
        /// </summary>
        public static string a_Cozunurluk {
            get {
                return ResourceManager.GetString("a_Cozunurluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPLA ve PPLB.
        /// </summary>
        public static string a_dil {
            get {
                return ResourceManager.GetString("a_dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 MB DRAM, 4 MB Flash Bellek.
        /// </summary>
        public static string a_hafiza {
            get {
                return ResourceManager.GetString("a_hafiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAZICILAR.
        /// </summary>
        public static string anaBaslik {
            get {
                return ResourceManager.GetString("anaBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskı Genişliği:.
        /// </summary>
        public static string BaskiGenişligi {
            get {
                return ResourceManager.GetString("BaskiGenişligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskı Hızı:.
        /// </summary>
        public static string BaskiHizi {
            get {
                return ResourceManager.GetString("BaskiHizi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskı Metodu:.
        /// </summary>
        public static string BaskiMetodu {
            get {
                return ResourceManager.GetString("BaskiMetodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskı Uzunluğu:.
        /// </summary>
        public static string BaskiUzunluk {
            get {
                return ResourceManager.GetString("BaskiUzunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASAÜSTÜ YAZICILAR.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çözünürlük:.
        /// </summary>
        public static string cozunurluk {
            get {
                return ResourceManager.GetString("cozunurluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DİĞER.
        /// </summary>
        public static string diger {
            get {
                return ResourceManager.GetString("diger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 108 mm.
        /// </summary>
        public static string ev_BaskiGenislik {
            get {
                return ResourceManager.GetString("ev_BaskiGenislik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127 mm.
        /// </summary>
        public static string ev_BaskiHizi {
            get {
                return ResourceManager.GetString("ev_BaskiHizi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direk termal (Ribonsuz) / Termal Transfer (Ribonlu).
        /// </summary>
        public static string ev_BaskiMetod {
            get {
                return ResourceManager.GetString("ev_BaskiMetod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 995 mm.
        /// </summary>
        public static string ev_BaskiUzunluk {
            get {
                return ResourceManager.GetString("ev_BaskiUzunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203 DPI.
        /// </summary>
        public static string ev_Cozunurluk {
            get {
                return ResourceManager.GetString("ev_Cozunurluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPL.
        /// </summary>
        public static string ev_dil {
            get {
                return ResourceManager.GetString("ev_dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 MB DRAM, 4 MB Flash Bellek.
        /// </summary>
        public static string ev_Hafiza {
            get {
                return ResourceManager.GetString("ev_Hafiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri+ Paralel + Usb 2.0 + Lan.
        /// </summary>
        public static string ev_Port {
            get {
                return ResourceManager.GetString("ev_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOSHIBA.
        /// </summary>
        public static string evBaslik1 {
            get {
                return ResourceManager.GetString("evBaslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-EV4T.
        /// </summary>
        public static string evBaslik2 {
            get {
                return ResourceManager.GetString("evBaslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En fazla 108 mm..
        /// </summary>
        public static string fv_BaskiGenislik {
            get {
                return ResourceManager.GetString("fv_BaskiGenislik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 152,4 mm..
        /// </summary>
        public static string fv_BaskiHizi {
            get {
                return ResourceManager.GetString("fv_BaskiHizi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direkt termal (Ribonsuz) Termal Transfer (Ribonlu).
        /// </summary>
        public static string fv_BaskiMetod {
            get {
                return ResourceManager.GetString("fv_BaskiMetod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 995 mm.
        /// </summary>
        public static string fv_BaskiUzunluk {
            get {
                return ResourceManager.GetString("fv_BaskiUzunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203 DPI.
        /// </summary>
        public static string fv_Cozunurluk {
            get {
                return ResourceManager.GetString("fv_Cozunurluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPCL.
        /// </summary>
        public static string fv_dil {
            get {
                return ResourceManager.GetString("fv_dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 MB DRAM, 4 MB Flash Bellek.
        /// </summary>
        public static string fv_Hafiza {
            get {
                return ResourceManager.GetString("fv_Hafiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri Port, Paralel Port, USB, LAN..
        /// </summary>
        public static string fv_iletisim {
            get {
                return ResourceManager.GetString("fv_iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri Port, Paralel Port, USB, LAN..
        /// </summary>
        public static string fv_Port {
            get {
                return ResourceManager.GetString("fv_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOSHIBA.
        /// </summary>
        public static string fvBaslik1 {
            get {
                return ResourceManager.GetString("fvBaslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-FV4T.
        /// </summary>
        public static string fvBaslik2 {
            get {
                return ResourceManager.GetString("fvBaslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hafıza:.
        /// </summary>
        public static string Hafiza {
            get {
                return ResourceManager.GetString("Hafiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Portları:.
        /// </summary>
        public static string iletisimPort {
            get {
                return ResourceManager.GetString("iletisimPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programlama Dilleri:.
        /// </summary>
        public static string ProgramDil {
            get {
                return ResourceManager.GetString("ProgramDil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜNLER.
        /// </summary>
        public static string urun {
            get {
                return ResourceManager.GetString("urun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104 mm104 mm..
        /// </summary>
        public static string z_BaskiGenislik {
            get {
                return ResourceManager.GetString("z_BaskiGenislik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102 mm/s..
        /// </summary>
        public static string z_BaskiHizi {
            get {
                return ResourceManager.GetString("z_BaskiHizi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direk Termal..
        /// </summary>
        public static string z_BaskiMetod {
            get {
                return ResourceManager.GetString("z_BaskiMetod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 991 mm..
        /// </summary>
        public static string z_baskiUzunluk {
            get {
                return ResourceManager.GetString("z_baskiUzunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203 dpi (8 dot/mm).
        /// </summary>
        public static string z_cozunurluk {
            get {
                return ResourceManager.GetString("z_cozunurluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPL2, ZPL I/ZPL II..
        /// </summary>
        public static string z_dil {
            get {
                return ResourceManager.GetString("z_dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standart; 8 MB SDRAM, 8 MB Flash..
        /// </summary>
        public static string z_hafiza {
            get {
                return ResourceManager.GetString("z_hafiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZEBRA.
        /// </summary>
        public static string zBaslik1 {
            get {
                return ResourceManager.GetString("zBaslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC-420T.
        /// </summary>
        public static string zBaslik2 {
            get {
                return ResourceManager.GetString("zBaslik2", resourceCulture);
            }
        }
    }
}
