//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KODMARK_new.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KODMARK_new.Resources.IndexText", typeof(IndexText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulduğu tarihten bu yana yurt içinde hizmet veren firmamız, 2017 itibariyle de 9 ülkeye ihracat yapmaya başlamıştır. Türkiye’de sürdürdüğü büyüme ile birlikte, daha çok ülkeye ulaşma hedefine adım adım yaklaşan, sürekli gelişim amacı gözeten bir firma olma yolunda başarısını sürdürmektedir..
        /// </summary>
        public static string b_aciklama {
            get {
                return ResourceManager.GetString("b_aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİZ.
        /// </summary>
        public static string b_baslik1 {
            get {
                return ResourceManager.GetString("b_baslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KODMARK&apos;IZ.
        /// </summary>
        public static string b_baslik2 {
            get {
                return ResourceManager.GetString("b_baslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İNŞAAT.
        /// </summary>
        public static string b_insaat {
            get {
                return ResourceManager.GetString("b_insaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KİMYA.
        /// </summary>
        public static string b_kimya {
            get {
                return ResourceManager.GetString("b_kimya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEKSTİL VE LOJİSTİC VB..
        /// </summary>
        public static string b_tekstilvelojistik {
            get {
                return ResourceManager.GetString("b_tekstilvelojistik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIDA.
        /// </summary>
        public static string b_yemek {
            get {
                return ResourceManager.GetString("b_yemek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket, Barkod, Barkod Okuyucu ve Yazıcı Ribon, El Terminalleri Wax Resin Ribon Barkod Programları Barkod Makinası Etiket Makinası.
        /// </summary>
        public static string s_aciklama {
            get {
                return ResourceManager.GetString("s_aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDÜSTRİYEL YAZICILAR.
        /// </summary>
        public static string s_endustriel {
            get {
                return ResourceManager.GetString("s_endustriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETİKETLER.
        /// </summary>
        public static string s_etiketler {
            get {
                return ResourceManager.GetString("s_etiketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASAÜSTÜ YAZICILAR.
        /// </summary>
        public static string s_masaustu {
            get {
                return ResourceManager.GetString("s_masaustu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKUYUCULAR.
        /// </summary>
        public static string s_okuyucu {
            get {
                return ResourceManager.GetString("s_okuyucu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RİBONLAR.
        /// </summary>
        public static string s_ribon {
            get {
                return ResourceManager.GetString("s_ribon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a mark....
        /// </summary>
        public static string s_slogan {
            get {
                return ResourceManager.GetString("s_slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DİĞER.
        /// </summary>
        public static string s_urunler1 {
            get {
                return ResourceManager.GetString("s_urunler1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜNLER.
        /// </summary>
        public static string s_urunler2 {
            get {
                return ResourceManager.GetString("s_urunler2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAZICI AKSESUARLARI.
        /// </summary>
        public static string s_yaziciAksesuar {
            get {
                return ResourceManager.GetString("s_yaziciAksesuar", resourceCulture);
            }
        }
    }
}
