//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodmark.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndustrialPrintersText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndustrialPrintersText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodmark.Resources.IndustrialPrintersText", typeof(IndustrialPrintersText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAZICILAR.
        /// </summary>
        public static string anaBaslik {
            get {
                return ResourceManager.GetString("anaBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDÜSTRİYEL YAZICILAR.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DİĞER.
        /// </summary>
        public static string diger {
            get {
                return ResourceManager.GetString("diger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOSHIBA B SERİSİ.
        /// </summary>
        public static string tabloToshibaYaziciAdi {
            get {
                return ResourceManager.GetString("tabloToshibaYaziciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZEBRA ZT SERİSİ.
        /// </summary>
        public static string tabloZebraYaziciAdi {
            get {
                return ResourceManager.GetString("tabloZebraYaziciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASKI.
        /// </summary>
        public static string toshibaBaski {
            get {
                return ResourceManager.GetString("toshibaBaski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direk Termal / Termal Transfer.
        /// </summary>
        public static string toshibabaski1 {
            get {
                return ResourceManager.GetString("toshibabaski1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direk Termal / Termal Transfer.
        /// </summary>
        public static string toshibabaski2 {
            get {
                return ResourceManager.GetString("toshibabaski2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direk Termal / Termal Transfer.
        /// </summary>
        public static string toshibabaski3 {
            get {
                return ResourceManager.GetString("toshibabaski3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direk Termal / Termal Transfer.
        /// </summary>
        public static string toshibabaski4 {
            get {
                return ResourceManager.GetString("toshibabaski4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASKI HIZI.
        /// </summary>
        public static string ToshibaBaskiHizi {
            get {
                return ResourceManager.GetString("ToshibaBaskiHizi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOSHIBA B.
        /// </summary>
        public static string toshibaBaslik1 {
            get {
                return ResourceManager.GetString("toshibaBaslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serisi.
        /// </summary>
        public static string toshibabaslik2 {
            get {
                return ResourceManager.GetString("toshibabaslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104 mm.
        /// </summary>
        public static string toshibaGenislik1 {
            get {
                return ResourceManager.GetString("toshibaGenislik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104 mm.
        /// </summary>
        public static string toshibaGenislik2 {
            get {
                return ResourceManager.GetString("toshibaGenislik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104 mm.
        /// </summary>
        public static string toshibaGenislik3 {
            get {
                return ResourceManager.GetString("toshibaGenislik3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.5 mm.
        /// </summary>
        public static string toshibaGenislik4 {
            get {
                return ResourceManager.GetString("toshibaGenislik4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 355.6 mm/s.
        /// </summary>
        public static string toshibahiz1 {
            get {
                return ResourceManager.GetString("toshibahiz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 304 mm/s.
        /// </summary>
        public static string toshibahiz2 {
            get {
                return ResourceManager.GetString("toshibahiz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 254 mm/s.
        /// </summary>
        public static string toshibahiz3 {
            get {
                return ResourceManager.GetString("toshibahiz3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203.2 mm/s.
        /// </summary>
        public static string toshibahiz4 {
            get {
                return ResourceManager.GetString("toshibahiz4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-EX4T1.
        /// </summary>
        public static string toshibamodel1 {
            get {
                return ResourceManager.GetString("toshibamodel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-EX4T2.
        /// </summary>
        public static string toshibamodel2 {
            get {
                return ResourceManager.GetString("toshibamodel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-SX4T.
        /// </summary>
        public static string toshibamodel3 {
            get {
                return ResourceManager.GetString("toshibamodel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-SX5T.
        /// </summary>
        public static string toshibamodel4 {
            get {
                return ResourceManager.GetString("toshibamodel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASKI GENİŞLİĞİ.
        /// </summary>
        public static string toshibaTabloBaskiGenisligi {
            get {
                return ResourceManager.GetString("toshibaTabloBaskiGenisligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜNLER.
        /// </summary>
        public static string urun {
            get {
                return ResourceManager.GetString("urun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebra ZT.
        /// </summary>
        public static string zebrabaslik1 {
            get {
                return ResourceManager.GetString("zebrabaslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serisi.
        /// </summary>
        public static string zebrabaslik2 {
            get {
                return ResourceManager.GetString("zebrabaslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104mm.
        /// </summary>
        public static string zebragenislik1 {
            get {
                return ResourceManager.GetString("zebragenislik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104mm.
        /// </summary>
        public static string zebragenislik2 {
            get {
                return ResourceManager.GetString("zebragenislik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104mm.
        /// </summary>
        public static string zebragenislik3 {
            get {
                return ResourceManager.GetString("zebragenislik3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 168mm.
        /// </summary>
        public static string zebragenislik4 {
            get {
                return ResourceManager.GetString("zebragenislik4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 152mm/sn.
        /// </summary>
        public static string zebrahiz1 {
            get {
                return ResourceManager.GetString("zebrahiz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 152mm/sn.
        /// </summary>
        public static string zebrahiz2 {
            get {
                return ResourceManager.GetString("zebrahiz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 356 mm/sn.
        /// </summary>
        public static string zebrahiz3 {
            get {
                return ResourceManager.GetString("zebrahiz3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 305mm/sn.
        /// </summary>
        public static string zebrahiz4 {
            get {
                return ResourceManager.GetString("zebrahiz4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZT-220.
        /// </summary>
        public static string zebramodel1 {
            get {
                return ResourceManager.GetString("zebramodel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZT-230.
        /// </summary>
        public static string zebramodel2 {
            get {
                return ResourceManager.GetString("zebramodel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZT-410.
        /// </summary>
        public static string zebramodel3 {
            get {
                return ResourceManager.GetString("zebramodel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZT-420.
        /// </summary>
        public static string zebramodel4 {
            get {
                return ResourceManager.GetString("zebramodel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direk Termal Ya da termal transfer.
        /// </summary>
        public static string zebraprint1 {
            get {
                return ResourceManager.GetString("zebraprint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direkt Termal ve Termal Transfer.
        /// </summary>
        public static string zebraprint2 {
            get {
                return ResourceManager.GetString("zebraprint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termal transfer ve direkt termal baskı.
        /// </summary>
        public static string zebraprint3 {
            get {
                return ResourceManager.GetString("zebraprint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termal transfer ve direkt termal baskı.
        /// </summary>
        public static string zebraprint4 {
            get {
                return ResourceManager.GetString("zebraprint4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASKI.
        /// </summary>
        public static string zebratabloBaski {
            get {
                return ResourceManager.GetString("zebratabloBaski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASKI GENİŞLİĞİ.
        /// </summary>
        public static string zebratabloBaskiGenislik {
            get {
                return ResourceManager.GetString("zebratabloBaskiGenislik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASKI HIZI.
        /// </summary>
        public static string zebratabloBaskiHizi {
            get {
                return ResourceManager.GetString("zebratabloBaskiHizi", resourceCulture);
            }
        }
    }
}
