//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KODMARK_new.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KODMARK_new.Resources.LayoutText", typeof(LayoutText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barkod Yazıcı Aksesuarları.
        /// </summary>
        public static string BarcodePrinterAccessories {
            get {
                return ResourceManager.GetString("BarcodePrinterAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barkod Okuyucular.
        /// </summary>
        public static string BarcodeReaders {
            get {
                return ResourceManager.GetString("BarcodeReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskısız Etiketler.
        /// </summary>
        public static string BlankLabel {
            get {
                return ResourceManager.GetString("BlankLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        public static string Corporate {
            get {
                return ResourceManager.GetString("Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masaüstü Barkod Yazıcılar.
        /// </summary>
        public static string DesktopBarcodePrinters {
            get {
                return ResourceManager.GetString("DesktopBarcodePrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanayi, Ensar Cd. No:35/3, 34899 Pendik/İstanbul.
        /// </summary>
        public static string f_adress {
            get {
                return ResourceManager.GetString("f_adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodmark Etiket Barkod Ambalaj Endüstrisi. ve Tic. Ltd. Şti..
        /// </summary>
        public static string f_adrestanim {
            get {
                return ResourceManager.GetString("f_adrestanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string f_ContactUs {
            get {
                return ResourceManager.GetString("f_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        public static string f_Pages {
            get {
                return ResourceManager.GetString("f_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a mark....
        /// </summary>
        public static string f_Slogan {
            get {
                return ResourceManager.GetString("f_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endüstriyel Barkod Yazıcılar.
        /// </summary>
        public static string IndustrialBarcodePrinters {
            get {
                return ResourceManager.GetString("IndustrialBarcodePrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiketler.
        /// </summary>
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil Barkod Yazıcılar.
        /// </summary>
        public static string MobilBarcodePrinters {
            get {
                return ResourceManager.GetString("MobilBarcodePrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskılı Etiketler.
        /// </summary>
        public static string PrintedLabel {
            get {
                return ResourceManager.GetString("PrintedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazıcılar.
        /// </summary>
        public static string Printers {
            get {
                return ResourceManager.GetString("Printers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ribonlar.
        /// </summary>
        public static string Ribbons {
            get {
                return ResourceManager.GetString("Ribbons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyon, Misyon ve Değerlerimiz.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
    }
}
