//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KODMARK_new.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MobilePrinterText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobilePrinterText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KODMARK_new.Resources.MobilePrinterText", typeof(MobilePrinterText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARGOX.
        /// </summary>
        public static string a_baslik1 {
            get {
                return ResourceManager.GetString("a_baslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AME 3230B.
        /// </summary>
        public static string a_baslik2 {
            get {
                return ResourceManager.GetString("a_baslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapışkanlı etiketede yazdırılabilir.
        /// </summary>
        public static string a_diger {
            get {
                return ResourceManager.GetString("a_diger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS-232,USB,IRDA ve Bluetooth PPLZ dil desteği.
        /// </summary>
        public static string a_dil {
            get {
                return ResourceManager.GetString("a_dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 72mm.
        /// </summary>
        public static string a_genislik {
            get {
                return ResourceManager.GetString("a_genislik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8MB DRAM ve 4MB Flash ROM bellek.
        /// </summary>
        public static string a_hafiza {
            get {
                return ResourceManager.GetString("a_hafiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76mm/sn.
        /// </summary>
        public static string a_hiz {
            get {
                return ResourceManager.GetString("a_hiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direk Termal.
        /// </summary>
        public static string a_metod {
            get {
                return ResourceManager.GetString("a_metod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 1016mm.
        /// </summary>
        public static string a_uzunluk {
            get {
                return ResourceManager.GetString("a_uzunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAZICILAR.
        /// </summary>
        public static string anaBaslik {
            get {
                return ResourceManager.GetString("anaBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskı Genişliği:.
        /// </summary>
        public static string baskiGenislik {
            get {
                return ResourceManager.GetString("baskiGenislik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskı Hızı:.
        /// </summary>
        public static string baskiHiz {
            get {
                return ResourceManager.GetString("baskiHiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskı Metodu:.
        /// </summary>
        public static string baskiMetod {
            get {
                return ResourceManager.GetString("baskiMetod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskı Uzunluğu:.
        /// </summary>
        public static string baskiUuzunluk {
            get {
                return ResourceManager.GetString("baskiUuzunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOBİL BARKOD YAZICILAR.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çözünürlük:.
        /// </summary>
        public static string cozunurluk {
            get {
                return ResourceManager.GetString("cozunurluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destekledikleri:.
        /// </summary>
        public static string destekledigi {
            get {
                return ResourceManager.GetString("destekledigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DİĞER.
        /// </summary>
        public static string diger {
            get {
                return ResourceManager.GetString("diger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğerleri:.
        /// </summary>
        public static string digerleri {
            get {
                return ResourceManager.GetString("digerleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Desteği:.
        /// </summary>
        public static string dilDestek {
            get {
                return ResourceManager.GetString("dilDestek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hafıza:.
        /// </summary>
        public static string hafiza {
            get {
                return ResourceManager.GetString("hafiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOSHIBA.
        /// </summary>
        public static string t_baslik1 {
            get {
                return ResourceManager.GetString("t_baslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-EP4DL.
        /// </summary>
        public static string t_baslik2 {
            get {
                return ResourceManager.GetString("t_baslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203dpi.
        /// </summary>
        public static string t_cozunurluk {
            get {
                return ResourceManager.GetString("t_cozunurluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16MB S-RAM,USB,Bluetooth.
        /// </summary>
        public static string t_destek {
            get {
                return ResourceManager.GetString("t_destek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104mm.
        /// </summary>
        public static string t_genisllik {
            get {
                return ResourceManager.GetString("t_genisllik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 105mm/s.
        /// </summary>
        public static string t_hiz {
            get {
                return ResourceManager.GetString("t_hiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direk Termal.
        /// </summary>
        public static string t_metod {
            get {
                return ResourceManager.GetString("t_metod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 997mm.
        /// </summary>
        public static string t_uzunluk {
            get {
                return ResourceManager.GetString("t_uzunluk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜNLER.
        /// </summary>
        public static string urun {
            get {
                return ResourceManager.GetString("urun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZEBRA İMZ.
        /// </summary>
        public static string zimz_baslik1 {
            get {
                return ResourceManager.GetString("zimz_baslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERİSİ.
        /// </summary>
        public static string zimz_baslik2 {
            get {
                return ResourceManager.GetString("zimz_baslik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebra’nın kompakt ve ergonomik tasarıma sahip taşınabilir yazıcıları serisinde yer alan İMZ220 ve İMZ320 model mobil yazıcılar sürekli baskının gerekli olduğu birçok uygulamada yoğun olarak kullanılmaktadır. Bluetooth veya 802,11b/g üzerinden baskı sağlanabilmektedir..
        /// </summary>
        public static string zimzAciklama {
            get {
                return ResourceManager.GetString("zimzAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebra QLn serisi taşınabilir yazıcılar, özellikle etiket basımı için tasarlanmış olup 100mm/sn baskı hızını desteklemektedir. QLn220 serisi 2”, QLn320 serisi 3”, QLn420 serisi ise 4” genişliğine baskı yapar. Bluetooth 2.0 veya 802.11b/g üzerinden bağlantı sağlanabilmektedir..
        /// </summary>
        public static string zqln_Aciklama {
            get {
                return ResourceManager.GetString("zqln_Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZEBRA QLN.
        /// </summary>
        public static string zqln_baslik1 {
            get {
                return ResourceManager.GetString("zqln_baslik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERİSİ.
        /// </summary>
        public static string zqln_baslik2 {
            get {
                return ResourceManager.GetString("zqln_baslik2", resourceCulture);
            }
        }
    }
}
