//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodmark.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrintedLabelText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintedLabelText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodmark.Resources.PrintedLabelText", typeof(PrintedLabelText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambalaj Etiketleri.
        /// </summary>
        public static string ambalaj {
            get {
                return ResourceManager.GetString("ambalaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASKILI ETİKETLER.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gıda Ürün Etiketleri.
        /// </summary>
        public static string gida {
            get {
                return ResourceManager.GetString("gida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimya Etiketleri.
        /// </summary>
        public static string kimya {
            get {
                return ResourceManager.GetString("kimya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koli Etiketleri.
        /// </summary>
        public static string koli {
            get {
                return ResourceManager.GetString("koli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kozmetik Etiketler.
        /// </summary>
        public static string kozmetik {
            get {
                return ResourceManager.GetString("kozmetik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madeni Yağ Etiketleri.
        /// </summary>
        public static string madeniYag {
            get {
                return ResourceManager.GetString("madeniYag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekstil Etiketleri.
        /// </summary>
        public static string tekstil {
            get {
                return ResourceManager.GetString("tekstil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizlik Ürün Etiketleri.
        /// </summary>
        public static string temizlik {
            get {
                return ResourceManager.GetString("temizlik", resourceCulture);
            }
        }
    }
}
