//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KODMARK_new.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RibonText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RibonText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KODMARK_new.Resources.RibonText", typeof(RibonText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RİBONLAR.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAYI.
        /// </summary>
        public static string detay {
            get {
                return ResourceManager.GetString("detay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotfoil Ribon.
        /// </summary>
        public static string hotfoil {
            get {
                return ResourceManager.GetString("hotfoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near Edge Ribon.
        /// </summary>
        public static string near {
            get {
                return ResourceManager.GetString("near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renkli Ribon.
        /// </summary>
        public static string renkli {
            get {
                return ResourceManager.GetString("renkli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resin Ribon.
        /// </summary>
        public static string resin {
            get {
                return ResourceManager.GetString("resin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih Kodlama / Hotfoil Ribon.
        /// </summary>
        public static string tarih {
            get {
                return ResourceManager.GetString("tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜN.
        /// </summary>
        public static string urun {
            get {
                return ResourceManager.GetString("urun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wax Ribon.
        /// </summary>
        public static string wax {
            get {
                return ResourceManager.GetString("wax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wax-Resin Ribon.
        /// </summary>
        public static string wax_resin {
            get {
                return ResourceManager.GetString("wax-resin", resourceCulture);
            }
        }
    }
}
