//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodmark.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VisionText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisionText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodmark.Resources.VisionText", typeof(VisionText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VİZYON, MİSYON VE DEĞERLERİMİZ.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Ahlakı:.
        /// </summary>
        public static string deger_h1 {
            get {
                return ResourceManager.GetString("deger_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenilirlik:.
        /// </summary>
        public static string deger_h2 {
            get {
                return ResourceManager.GetString("deger_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarma Tutkusu:.
        /// </summary>
        public static string deger_h3 {
            get {
                return ResourceManager.GetString("deger_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite Odaklılık:.
        /// </summary>
        public static string deger_h4 {
            get {
                return ResourceManager.GetString("deger_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumluluk:.
        /// </summary>
        public static string deger_h5 {
            get {
                return ResourceManager.GetString("deger_h5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün faaliyetler alanlarında, kararlarında ve ilişkilerinde en yüksek ahlaki değerleri göz önünde bulundurur..
        /// </summary>
        public static string deger_p1 {
            get {
                return ResourceManager.GetString("deger_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birbirimize, iş ortaklarımıza ve müşterilerimize karşı açık, içten, dürüst ve adil davranırız. Güven ve dürüstlük en önemli değerimizdir..
        /// </summary>
        public static string deger_p2 {
            get {
                return ResourceManager.GetString("deger_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarı tutkumuzun yüksek olmasının vermiş olduğu duyguyla zorluklar karşısında pes etmez, mücadele eder ve yüksek motivasyonla çalışırız..
        /// </summary>
        public static string deger_p3 {
            get {
                return ResourceManager.GetString("deger_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlerimizi zamanında, en kaliteli ve verimli şekilde tamamlarız..
        /// </summary>
        public static string deger_p4 {
            get {
                return ResourceManager.GetString("deger_p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşimizle ilgili beklentileri doğru anlar ve sorumluluk üstleniriz, etkin çözümler önerir ve uygularız..
        /// </summary>
        public static string deger_p5 {
            get {
                return ResourceManager.GetString("deger_p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEĞERLERİMİZ.
        /// </summary>
        public static string degerlerimiz {
            get {
                return ResourceManager.GetString("degerlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MİSYONUMUZ.
        /// </summary>
        public static string misyon {
            get {
                return ResourceManager.GetString("misyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sürekli iyileştirmeyi ilke edinmek..
        /// </summary>
        public static string misyon_p1 {
            get {
                return ResourceManager.GetString("misyon_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim kapasitesini arttırmak..
        /// </summary>
        public static string misyon_p2 {
            get {
                return ResourceManager.GetString("misyon_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenilikçi ve pozitif yönetimi esas almak..
        /// </summary>
        public static string misyon_p3 {
            get {
                return ResourceManager.GetString("misyon_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaliteye önem vermek..
        /// </summary>
        public static string misyon_p4 {
            get {
                return ResourceManager.GetString("misyon_p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VİZYONUMUZ.
        /// </summary>
        public static string vision {
            get {
                return ResourceManager.GetString("vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzman kadrosu ile hizmet ve ürün kalitesini bütünleştirip, müşterilerinin ilk tercihi olarak geniş kitlelere ulaşabilmek..
        /// </summary>
        public static string vizyonAciklama {
            get {
                return ResourceManager.GetString("vizyonAciklama", resourceCulture);
            }
        }
    }
}
